module HelloWorldTestingggg
  module Internal
    module Type
      module BaseStream[Message, Elem]
        include Enumerable[Elem]

        attr_reader status: Integer

        attr_reader headers: ::Hash[String, String]

        def close: -> void

        private def iterator: -> Enumerable[Elem]

        def each: { (Elem arg0) -> void } -> void

        def to_enum: -> Enumerator[Elem]

        alias enum_for to_enum

        def initialize: (
          model: Class | HelloWorldTestingggg::Internal::Type::Converter,
          url: URI::Generic,
          status: Integer,
          headers: ::Hash[String, String],
          response: top,
          unwrap: Symbol
          | Integer
          | ::Array[Symbol | Integer]
          | ^(top arg0) -> top,
          stream: Enumerable[Message]
        ) -> void

        def inspect: -> String
      end
    end
  end
end
