module HelloWorldTestingggg
  module Models
    module Store
      type order_retrieve_response =
        {
          id: Integer,
          complete: bool,
          pet_id: Integer,
          quantity: Integer,
          ship_date: Time,
          status: HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status
        }

      class OrderRetrieveResponse < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader complete: bool?

        def complete=: (bool) -> bool

        attr_reader pet_id: Integer?

        def pet_id=: (Integer) -> Integer

        attr_reader quantity: Integer?

        def quantity=: (Integer) -> Integer

        attr_reader ship_date: Time?

        def ship_date=: (Time) -> Time

        attr_reader status: HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status?

        def status=: (
          HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status
        ) -> HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status

        def initialize: (
          ?id: Integer,
          ?complete: bool,
          ?pet_id: Integer,
          ?quantity: Integer,
          ?ship_date: Time,
          ?status: HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status
        ) -> void

        def to_hash: -> {
          id: Integer,
          complete: bool,
          pet_id: Integer,
          quantity: Integer,
          ship_date: Time,
          status: HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status
        }

        type status = :placed | :approved | :delivered

        module Status
          extend HelloWorldTestingggg::Internal::Type::Enum

          PLACED: :placed
          APPROVED: :approved
          DELIVERED: :delivered

          def self?.values: -> ::Array[HelloWorldTestingggg::Models::Store::OrderRetrieveResponse::status]
        end
      end
    end
  end
end
