module HelloWorldTestingggg
  module Models
    module Store
      type report_list =
        { data: ::Array[HelloWorldTestingggg::Store::Report], has_more: bool }

      class ReportList < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_accessor data: ::Array[HelloWorldTestingggg::Store::Report]

        attr_accessor has_more: bool

        def initialize: (
          data: ::Array[HelloWorldTestingggg::Store::Report],
          has_more: bool
        ) -> void

        def to_hash: -> {
          data: ::Array[HelloWorldTestingggg::Store::Report],
          has_more: bool
        }
      end
    end
  end
end
