module HelloWorldTestingggg
  module Resources
    class Pet
      def create: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?acquisition_channel: HelloWorldTestingggg::Models::PetAPI::acquisition_channel,
        ?category: HelloWorldTestingggg::PetAPI::Category,
        ?microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        ?status: HelloWorldTestingggg::Models::pet_status,
        ?tags: ::Array[HelloWorldTestingggg::PetAPI::Tag],
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::PetAPI

      def retrieve: (
        Integer pet_id,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::PetAPI

      def update: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?acquisition_channel: HelloWorldTestingggg::Models::PetAPI::acquisition_channel,
        ?category: HelloWorldTestingggg::PetAPI::Category,
        ?microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        ?status: HelloWorldTestingggg::Models::pet_status,
        ?tags: ::Array[HelloWorldTestingggg::PetAPI::Tag],
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::PetAPI

      def list: (
        ?created_at: HelloWorldTestingggg::PetListParams::CreatedAt,
        ?cursor: String,
        ?limit: Integer,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Internal::CustomCursorPage[HelloWorldTestingggg::PetAPI]

      def delete: (
        Integer pet_id,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> nil

      def find_by_status: (
        ?status: HelloWorldTestingggg::Models::PetFindByStatusParams::status,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::pet_find_by_status_response

      def find_by_tags: (
        ?tags: ::Array[String],
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::pet_find_by_tags_response

      def list_fake_page: (
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::PetListFakePageResponse

      def list_fake_page_inferred: (
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Internal::XFakeSinglePage[HelloWorldTestingggg::PetAPI]

      def list_leaderboard: (
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::pet_list_leaderboard_response

      def list_unpaginated: (
        ?cursor: String,
        ?limit: Integer,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::PetListUnpaginatedResponse

      def retrieve_premium: (
        Integer pet_id,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::PetRetrievePremiumResponse

      def search: (
        ?filters: HelloWorldTestingggg::PetSearchParams::Filters,
        ?max_results: Integer,
        ?raw_filter: top,
        ?tag_filters: ::Array[HelloWorldTestingggg::PetSearchParams::TagFilter],
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::pet_search_response

      def update_with_form: (
        Integer pet_id,
        ?name: String,
        ?status: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> nil

      def upload_image: (
        Integer pet_id,
        body: HelloWorldTestingggg::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::PetUploadImageResponse

      def watch_status_streaming: (
        Integer pet_id,
        ?last_event_id: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Internal::Stream[HelloWorldTestingggg::PetAPI]

      def initialize: (client: HelloWorldTestingggg::Client) -> void
    end
  end
end
