module HelloWorldTestingggg
  module Resources
    class Store
      attr_reader order: HelloWorldTestingggg::Resources::Store::Order

      attr_reader reports: HelloWorldTestingggg::Resources::Store::Reports

      def list_inventory: (
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::store_list_inventory_response

      def retrieve_activity: (
        String activity_id,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> HelloWorldTestingggg::Models::store_retrieve_activity_response

      def initialize: (client: HelloWorldTestingggg::Client) -> void
    end
  end
end
