module HelloWorldTestingggg
  module Internal
    class ReportCursorPage[Elem]
      include HelloWorldTestingggg::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor has_more: bool

      def inspect: -> String
    end
  end
end
