module HelloWorldTestingggg
  class Client < HelloWorldTestingggg::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader basic_auth_username: String

    attr_reader basic_auth_password: String

    attr_reader webhook_secret: String?

    attr_reader pet: HelloWorldTestingggg::Resources::Pet

    attr_reader files: HelloWorldTestingggg::Resources::Files

    attr_reader profiles: HelloWorldTestingggg::Resources::Profiles

    attr_reader adoptions: HelloWorldTestingggg::Resources::Adoptions

    attr_reader placements: HelloWorldTestingggg::Resources::Placements

    attr_reader veterinary: HelloWorldTestingggg::Resources::Veterinary

    attr_reader webhooks: HelloWorldTestingggg::Resources::Webhooks

    attr_reader notifications: HelloWorldTestingggg::Resources::Notifications

    attr_reader store: HelloWorldTestingggg::Resources::Store

    attr_reader user: HelloWorldTestingggg::Resources::User

    attr_reader ai: HelloWorldTestingggg::Resources::AI

    attr_reader media: HelloWorldTestingggg::Resources::Media

    def health: (
      ?request_options: HelloWorldTestingggg::request_opts
    ) -> HelloWorldTestingggg::SystemHealth

    def retrieve_rate_limits: (
      ?request_options: HelloWorldTestingggg::request_opts
    ) -> HelloWorldTestingggg::Models::RetrieveRateLimitsResponse

    private def auth_headers: -> ::Hash[String, String]

    private def auth_api_key: -> ::Hash[String, String]

    private def basic_auth: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?basic_auth_username: String?,
      ?basic_auth_password: String?,
      ?webhook_secret: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
