module HelloWorldTestingggg
  class Address = HelloWorldTestingggg::Models::Address

  class AdoptionCreateParams = HelloWorldTestingggg::Models::AdoptionCreateParams

  class AdoptionRetrieveDecisionParams = HelloWorldTestingggg::Models::AdoptionRetrieveDecisionParams

  class AdoptionRetrieveParams = HelloWorldTestingggg::Models::AdoptionRetrieveParams

  module Adoptions = HelloWorldTestingggg::Models::Adoptions

  class AdoptionsPolicyChangedWebhookEvent = HelloWorldTestingggg::Models::AdoptionsPolicyChangedWebhookEvent

  class AIAIQueryParams = HelloWorldTestingggg::Models::AIAIQueryParams

  class Application = HelloWorldTestingggg::Models::Application

  class Archive = HelloWorldTestingggg::Models::Archive

  class ClientHealthParams = HelloWorldTestingggg::Models::ClientHealthParams

  class ClientRetrieveRateLimitsParams = HelloWorldTestingggg::Models::ClientRetrieveRateLimitsParams

  class File = HelloWorldTestingggg::Models::File

  class FileCreateArchiveParams = HelloWorldTestingggg::Models::FileCreateArchiveParams

  class FileDeleteParams = HelloWorldTestingggg::Models::FileDeleteParams

  class FileDownloadParams = HelloWorldTestingggg::Models::FileDownloadParams

  class FileListParams = HelloWorldTestingggg::Models::FileListParams

  class Fileslist = HelloWorldTestingggg::Models::Fileslist

  class FileUpdateParams = HelloWorldTestingggg::Models::FileUpdateParams

  class FileUploadDirectParams = HelloWorldTestingggg::Models::FileUploadDirectParams

  class FileUploadParams = HelloWorldTestingggg::Models::FileUploadParams

  class MediaBinaryAndJsonParams = HelloWorldTestingggg::Models::MediaBinaryAndJsonParams

  class MediaJsonAndXmlParams = HelloWorldTestingggg::Models::MediaJsonAndXmlParams

  class MediaJsonFirstParams = HelloWorldTestingggg::Models::MediaJsonFirstParams

  class MediaSchemaOnJsonParams = HelloWorldTestingggg::Models::MediaSchemaOnJsonParams

  class MediaSchemaOnTextParams = HelloWorldTestingggg::Models::MediaSchemaOnTextParams

  class MediaTextFirstParams = HelloWorldTestingggg::Models::MediaTextFirstParams

  class MediaTextOnlyParams = HelloWorldTestingggg::Models::MediaTextOnlyParams

  class MediaVendorJsonParams = HelloWorldTestingggg::Models::MediaVendorJsonParams

  class MedicalSummary = HelloWorldTestingggg::Models::MedicalSummary

  class Money = HelloWorldTestingggg::Models::Money

  module Notifications = HelloWorldTestingggg::Models::Notifications

  module ParsedWebhookEvent = HelloWorldTestingggg::Models::ParsedWebhookEvent

  class PetAPI = HelloWorldTestingggg::Models::PetAPI

  class PetConnectParams = HelloWorldTestingggg::Models::PetConnectParams

  class PetCreatedWebhookEvent = HelloWorldTestingggg::Models::PetCreatedWebhookEvent

  class PetCreateParams = HelloWorldTestingggg::Models::PetCreateParams

  class PetDeleteParams = HelloWorldTestingggg::Models::PetDeleteParams

  class PetFindByStatusParams = HelloWorldTestingggg::Models::PetFindByStatusParams

  class PetFindByTagsParams = HelloWorldTestingggg::Models::PetFindByTagsParams

  class PetInventoryLowWebhookEvent = HelloWorldTestingggg::Models::PetInventoryLowWebhookEvent

  class PetListFakePageInferredParams = HelloWorldTestingggg::Models::PetListFakePageInferredParams

  class PetListFakePageParams = HelloWorldTestingggg::Models::PetListFakePageParams

  class PetListLeaderboardParams = HelloWorldTestingggg::Models::PetListLeaderboardParams

  class PetListParams = HelloWorldTestingggg::Models::PetListParams

  class PetListUnpaginatedParams = HelloWorldTestingggg::Models::PetListUnpaginatedParams

  module PetModerationWebhookEvent = HelloWorldTestingggg::Models::PetModerationWebhookEvent

  class PetRetrieveParams = HelloWorldTestingggg::Models::PetRetrieveParams

  class PetRetrievePremiumParams = HelloWorldTestingggg::Models::PetRetrievePremiumParams

  class PetSearchParams = HelloWorldTestingggg::Models::PetSearchParams

  module PetStatus = HelloWorldTestingggg::Models::PetStatus

  class PetUpdatedWebhookEvent = HelloWorldTestingggg::Models::PetUpdatedWebhookEvent

  class PetUpdateParams = HelloWorldTestingggg::Models::PetUpdateParams

  class PetUpdateWithFormParams = HelloWorldTestingggg::Models::PetUpdateWithFormParams

  class PetUploadImageParams = HelloWorldTestingggg::Models::PetUploadImageParams

  class PetWatchStatusParams = HelloWorldTestingggg::Models::PetWatchStatusParams

  class Placement = HelloWorldTestingggg::Models::Placement

  class PlacementCreateParams = HelloWorldTestingggg::Models::PlacementCreateParams

  module PlacementEvent = HelloWorldTestingggg::Models::PlacementEvent

  class PlacementEventRecordedWebhookEvent = HelloWorldTestingggg::Models::PlacementEventRecordedWebhookEvent

  class PlacementListParams = HelloWorldTestingggg::Models::PlacementListParams

  class PlacementRecordEventParams = HelloWorldTestingggg::Models::PlacementRecordEventParams

  class PlacementRetrieveParams = HelloWorldTestingggg::Models::PlacementRetrieveParams

  class Profile = HelloWorldTestingggg::Models::Profile

  class ProfileCreateParams = HelloWorldTestingggg::Models::ProfileCreateParams

  class ProfileCreateRequest = HelloWorldTestingggg::Models::ProfileCreateRequest

  class ProfileLegacySearchParams = HelloWorldTestingggg::Models::ProfileLegacySearchParams

  class ProfileRetrieveParams = HelloWorldTestingggg::Models::ProfileRetrieveParams

  class ProfileUpdateParams = HelloWorldTestingggg::Models::ProfileUpdateParams

  module Store = HelloWorldTestingggg::Models::Store

  class StoreListInventoryParams = HelloWorldTestingggg::Models::StoreListInventoryParams

  class StoreReportGeneratedWebhookEvent = HelloWorldTestingggg::Models::StoreReportGeneratedWebhookEvent

  class SystemHealth = HelloWorldTestingggg::Models::SystemHealth

  class TransferLeg = HelloWorldTestingggg::Models::TransferLeg

  class UserCreateParams = HelloWorldTestingggg::Models::UserCreateParams

  class UserCreateWithListParams = HelloWorldTestingggg::Models::UserCreateWithListParams

  class UserDeleteParams = HelloWorldTestingggg::Models::UserDeleteParams

  class UserLoginParams = HelloWorldTestingggg::Models::UserLoginParams

  class UserLogoutParams = HelloWorldTestingggg::Models::UserLogoutParams

  class UserRetrieveParams = HelloWorldTestingggg::Models::UserRetrieveParams

  class UserUpdateParams = HelloWorldTestingggg::Models::UserUpdateParams

  class UserVerifyIdentityParams = HelloWorldTestingggg::Models::UserVerifyIdentityParams

  class VaccinationRecord = HelloWorldTestingggg::Models::VaccinationRecord

  class WebhookParsedParams = HelloWorldTestingggg::Models::WebhookParsedParams
end
