module HelloWorldTestingggg
  module Resources
    class Store
      class Order
        def create: (
          ?id: Integer,
          ?complete: bool,
          ?pet_id: Integer,
          ?quantity: Integer,
          ?related_address: HelloWorldTestingggg::Address,
          ?related_category: top,
          ?related_customer: top,
          ?related_money: HelloWorldTestingggg::Money,
          ?related_pet: HelloWorldTestingggg::PetAPI,
          ?related_shelter: top,
          ?related_tag: top,
          ?related_user: top,
          ?ship_date: Time,
          ?status: HelloWorldTestingggg::Models::Store::OrderCreateParams::status,
          ?total: HelloWorldTestingggg::Money,
          ?request_options: HelloWorldTestingggg::request_opts
        ) -> HelloWorldTestingggg::Models::Store::OrderCreateResponse

        def retrieve: (
          Integer order_id,
          ?request_options: HelloWorldTestingggg::request_opts
        ) -> HelloWorldTestingggg::Models::Store::OrderRetrieveResponse

        def delete: (
          Integer order_id,
          ?request_options: HelloWorldTestingggg::request_opts
        ) -> nil

        def initialize: (client: HelloWorldTestingggg::Client) -> void
      end
    end
  end
end
