module HelloWorldTestingggg
  module Models
    type address =
      {
        city: String,
        geo: HelloWorldTestingggg::Address::Geo,
        related_category: top,
        related_customer: top,
        related_money: HelloWorldTestingggg::Money,
        related_order: top,
        related_pet: HelloWorldTestingggg::PetAPI,
        related_shelter: top,
        related_tag: top,
        related_user: top,
        state: String,
        street: String,
        zip: String
      }

    class Address < HelloWorldTestingggg::Internal::Type::BaseModel
      attr_reader city: String?

      def city=: (String) -> String

      attr_reader geo: HelloWorldTestingggg::Address::Geo?

      def geo=: (
        HelloWorldTestingggg::Address::Geo
      ) -> HelloWorldTestingggg::Address::Geo

      attr_reader related_category: top?

      def related_category=: (top) -> top

      attr_reader related_customer: top?

      def related_customer=: (top) -> top

      attr_reader related_money: HelloWorldTestingggg::Money?

      def related_money=: (
        HelloWorldTestingggg::Money
      ) -> HelloWorldTestingggg::Money

      attr_reader related_order: top?

      def related_order=: (top) -> top

      attr_reader related_pet: HelloWorldTestingggg::PetAPI?

      def related_pet=: (
        HelloWorldTestingggg::PetAPI
      ) -> HelloWorldTestingggg::PetAPI

      attr_reader related_shelter: top?

      def related_shelter=: (top) -> top

      attr_reader related_tag: top?

      def related_tag=: (top) -> top

      attr_reader related_user: top?

      def related_user=: (top) -> top

      attr_reader state: String?

      def state=: (String) -> String

      attr_reader street: String?

      def street=: (String) -> String

      attr_reader zip: String?

      def zip=: (String) -> String

      def initialize: (
        ?city: String,
        ?geo: HelloWorldTestingggg::Address::Geo,
        ?related_category: top,
        ?related_customer: top,
        ?related_money: HelloWorldTestingggg::Money,
        ?related_order: top,
        ?related_pet: HelloWorldTestingggg::PetAPI,
        ?related_shelter: top,
        ?related_tag: top,
        ?related_user: top,
        ?state: String,
        ?street: String,
        ?zip: String
      ) -> void

      def to_hash: -> {
        city: String,
        geo: HelloWorldTestingggg::Address::Geo,
        related_category: top,
        related_customer: top,
        related_money: HelloWorldTestingggg::Money,
        related_order: top,
        related_pet: HelloWorldTestingggg::PetAPI,
        related_shelter: top,
        related_tag: top,
        related_user: top,
        state: String,
        street: String,
        zip: String
      }

      type geo = { latitude: Float, longitude: Float }

      class Geo < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_accessor latitude: Float

        attr_accessor longitude: Float

        def initialize: (latitude: Float, longitude: Float) -> void

        def to_hash: -> { latitude: Float, longitude: Float }
      end
    end
  end
end
