module HelloWorldTestingggg
  module Models
    type file_delete_params =
      { path: String }
      & HelloWorldTestingggg::Internal::Type::request_parameters

    class FileDeleteParams < HelloWorldTestingggg::Internal::Type::BaseModel
      extend HelloWorldTestingggg::Internal::Type::RequestParameters::Converter
      include HelloWorldTestingggg::Internal::Type::RequestParameters

      attr_accessor path: String

      def initialize: (
        path: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> void

      def to_hash: -> {
        path: String,
        request_options: HelloWorldTestingggg::RequestOptions
      }
    end
  end
end
