module HelloWorldTestingggg
  module Models
    type media_schema_on_json_response = { id: String, label: String }

    class MediaSchemaOnJsonResponse < HelloWorldTestingggg::Internal::Type::BaseModel
      attr_accessor id: String

      attr_reader label: String?

      def label=: (String) -> String

      def initialize: (id: String, ?label: String) -> void

      def to_hash: -> { id: String, label: String }
    end
  end
end
