module HelloWorldTestingggg
  module Models
    type pet_api =
      {
        name: String,
        photo_urls: ::Array[String],
        id: Integer,
        acquisition_channel: HelloWorldTestingggg::Models::PetAPI::acquisition_channel,
        category: top,
        microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        related_address: HelloWorldTestingggg::Address,
        related_category: top,
        related_customer: top,
        related_money: HelloWorldTestingggg::Money,
        related_order: top,
        related_pet: HelloWorldTestingggg::PetAPI,
        related_shelter: top,
        related_user: top,
        status: HelloWorldTestingggg::Models::pet_status,
        tags: ::Array[top]
      }

    class PetAPI < HelloWorldTestingggg::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor photo_urls: ::Array[String]

      attr_reader id: Integer?

      def id=: (Integer) -> Integer

      attr_reader acquisition_channel: HelloWorldTestingggg::Models::PetAPI::acquisition_channel?

      def acquisition_channel=: (
        HelloWorldTestingggg::Models::PetAPI::acquisition_channel
      ) -> HelloWorldTestingggg::Models::PetAPI::acquisition_channel

      attr_reader category: top?

      def category=: (top) -> top

      attr_reader microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id?

      def microchip_id=: (
        HelloWorldTestingggg::Models::PetAPI::microchip_id
      ) -> HelloWorldTestingggg::Models::PetAPI::microchip_id

      attr_reader related_address: HelloWorldTestingggg::Address?

      def related_address=: (
        HelloWorldTestingggg::Address
      ) -> HelloWorldTestingggg::Address

      attr_reader related_category: top?

      def related_category=: (top) -> top

      attr_reader related_customer: top?

      def related_customer=: (top) -> top

      attr_reader related_money: HelloWorldTestingggg::Money?

      def related_money=: (
        HelloWorldTestingggg::Money
      ) -> HelloWorldTestingggg::Money

      attr_reader related_order: top?

      def related_order=: (top) -> top

      attr_reader related_pet: HelloWorldTestingggg::PetAPI?

      def related_pet=: (
        HelloWorldTestingggg::PetAPI
      ) -> HelloWorldTestingggg::PetAPI

      attr_reader related_shelter: top?

      def related_shelter=: (top) -> top

      attr_reader related_user: top?

      def related_user=: (top) -> top

      attr_reader status: HelloWorldTestingggg::Models::pet_status?

      def status=: (
        HelloWorldTestingggg::Models::pet_status
      ) -> HelloWorldTestingggg::Models::pet_status

      attr_reader tags: ::Array[top]?

      def tags=: (::Array[top]) -> ::Array[top]

      def initialize: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?acquisition_channel: HelloWorldTestingggg::Models::PetAPI::acquisition_channel,
        ?category: top,
        ?microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        ?related_address: HelloWorldTestingggg::Address,
        ?related_category: top,
        ?related_customer: top,
        ?related_money: HelloWorldTestingggg::Money,
        ?related_order: top,
        ?related_pet: HelloWorldTestingggg::PetAPI,
        ?related_shelter: top,
        ?related_user: top,
        ?status: HelloWorldTestingggg::Models::pet_status,
        ?tags: ::Array[top]
      ) -> void

      def to_hash: -> {
        name: String,
        photo_urls: ::Array[String],
        id: Integer,
        acquisition_channel: HelloWorldTestingggg::Models::PetAPI::acquisition_channel,
        category: top,
        microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        related_address: HelloWorldTestingggg::Address,
        related_category: top,
        related_customer: top,
        related_money: HelloWorldTestingggg::Money,
        related_order: top,
        related_pet: HelloWorldTestingggg::PetAPI,
        related_shelter: top,
        related_user: top,
        status: HelloWorldTestingggg::Models::pet_status,
        tags: ::Array[top]
      }

      type acquisition_channel =
        :breeder | :shelter | :surrender | :transfer | String

      module AcquisitionChannel
        extend HelloWorldTestingggg::Internal::Type::Union

        def self?.variants: -> ::Array[HelloWorldTestingggg::Models::PetAPI::acquisition_channel]

        BREEDER: :breeder
        SHELTER: :shelter
        SURRENDER: :surrender
        TRANSFER: :transfer
      end

      type microchip_id = String | Integer

      module MicrochipID
        extend HelloWorldTestingggg::Internal::Type::Union

        def self?.variants: -> ::Array[HelloWorldTestingggg::Models::PetAPI::microchip_id]
      end
    end
  end
end
