module HelloWorldTestingggg
  module Models
    type pet_api =
      {
        name: String,
        photo_urls: ::Array[String],
        id: Integer,
        category: HelloWorldTestingggg::PetAPI::Category,
        microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        status: HelloWorldTestingggg::Models::pet_status,
        tags: ::Array[HelloWorldTestingggg::PetAPI::Tag]
      }

    class PetAPI < HelloWorldTestingggg::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor photo_urls: ::Array[String]

      attr_reader id: Integer?

      def id=: (Integer) -> Integer

      attr_reader category: HelloWorldTestingggg::PetAPI::Category?

      def category=: (
        HelloWorldTestingggg::PetAPI::Category
      ) -> HelloWorldTestingggg::PetAPI::Category

      attr_reader microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id?

      def microchip_id=: (
        HelloWorldTestingggg::Models::PetAPI::microchip_id
      ) -> HelloWorldTestingggg::Models::PetAPI::microchip_id

      attr_reader status: HelloWorldTestingggg::Models::pet_status?

      def status=: (
        HelloWorldTestingggg::Models::pet_status
      ) -> HelloWorldTestingggg::Models::pet_status

      attr_reader tags: ::Array[HelloWorldTestingggg::PetAPI::Tag]?

      def tags=: (
        ::Array[HelloWorldTestingggg::PetAPI::Tag]
      ) -> ::Array[HelloWorldTestingggg::PetAPI::Tag]

      def initialize: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: HelloWorldTestingggg::PetAPI::Category,
        ?microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        ?status: HelloWorldTestingggg::Models::pet_status,
        ?tags: ::Array[HelloWorldTestingggg::PetAPI::Tag]
      ) -> void

      def to_hash: -> {
        name: String,
        photo_urls: ::Array[String],
        id: Integer,
        category: HelloWorldTestingggg::PetAPI::Category,
        microchip_id: HelloWorldTestingggg::Models::PetAPI::microchip_id,
        status: HelloWorldTestingggg::Models::pet_status,
        tags: ::Array[HelloWorldTestingggg::PetAPI::Tag]
      }

      type category = { id: Integer, name: String, subcategories: ::Array[top] }

      class Category < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader subcategories: ::Array[top]?

        def subcategories=: (::Array[top]) -> ::Array[top]

        def initialize: (
          ?id: Integer,
          ?name: String,
          ?subcategories: ::Array[top]
        ) -> void

        def to_hash: -> {
          id: Integer,
          name: String,
          subcategories: ::Array[top]
        }
      end

      type microchip_id = String | Integer

      module MicrochipID
        extend HelloWorldTestingggg::Internal::Type::Union

        def self?.variants: -> ::Array[HelloWorldTestingggg::Models::PetAPI::microchip_id]
      end

      type tag = { id: Integer, name: String }

      class Tag < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?id: Integer, ?name: String) -> void

        def to_hash: -> { id: Integer, name: String }
      end
    end
  end
end
