module HelloWorldTestingggg
  module Models
    type pet_update_with_form_params =
      { pet_id: Integer, name: String, status: String }
      & HelloWorldTestingggg::Internal::Type::request_parameters

    class PetUpdateWithFormParams < HelloWorldTestingggg::Internal::Type::BaseModel
      extend HelloWorldTestingggg::Internal::Type::RequestParameters::Converter
      include HelloWorldTestingggg::Internal::Type::RequestParameters

      attr_accessor pet_id: Integer

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        pet_id: Integer,
        ?name: String,
        ?status: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> void

      def to_hash: -> {
        pet_id: Integer,
        name: String,
        status: String,
        request_options: HelloWorldTestingggg::RequestOptions
      }
    end
  end
end
