module HelloWorldTestingggg
  module Models
    type pet_find_by_tags_response = ::Array[HelloWorldTestingggg::PetAPI]

    PetFindByTagsResponse: HelloWorldTestingggg::Internal::Type::Converter
  end
end
