module HelloWorldTestingggg
  module Models
    type pet_list_fake_page_response =
      { data: ::Array[HelloWorldTestingggg::PetAPI], has_more: bool }

    class PetListFakePageResponse < HelloWorldTestingggg::Internal::Type::BaseModel
      attr_accessor data: ::Array[HelloWorldTestingggg::PetAPI]

      attr_accessor has_more: bool

      def initialize: (
        data: ::Array[HelloWorldTestingggg::PetAPI],
        has_more: bool
      ) -> void

      def to_hash: -> {
        data: ::Array[HelloWorldTestingggg::PetAPI],
        has_more: bool
      }
    end
  end
end
