module HelloWorldTestingggg
  module Models
    type pet_upload_image_params =
      {
        pet_id: Integer,
        body: HelloWorldTestingggg::Internal::file_input,
        additional_metadata: String
      }
      & HelloWorldTestingggg::Internal::Type::request_parameters

    class PetUploadImageParams < HelloWorldTestingggg::Internal::Type::BaseModel
      extend HelloWorldTestingggg::Internal::Type::RequestParameters::Converter
      include HelloWorldTestingggg::Internal::Type::RequestParameters

      attr_accessor pet_id: Integer

      attr_accessor body: HelloWorldTestingggg::Internal::file_input

      attr_reader additional_metadata: String?

      def additional_metadata=: (String) -> String

      def initialize: (
        pet_id: Integer,
        body: HelloWorldTestingggg::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> void

      def to_hash: -> {
        pet_id: Integer,
        body: HelloWorldTestingggg::Internal::file_input,
        additional_metadata: String,
        request_options: HelloWorldTestingggg::RequestOptions
      }
    end
  end
end
