module HelloWorldTestingggg
  module Models
    type pet_upload_image_response =
      { code: Integer, message: String, type: String }

    class PetUploadImageResponse < HelloWorldTestingggg::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (?code: Integer, ?message: String, ?type: String) -> void

      def to_hash: -> { code: Integer, message: String, type: String }
    end
  end
end
