module HelloWorldTestingggg
  module Models
    type pet_moderation_webhook_event =
      HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationApproved
      | HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected

    module PetModerationWebhookEvent
      extend HelloWorldTestingggg::Internal::Type::Union

      type pet_moderation_approved =
        {
          approved_at: Time,
          pet: HelloWorldTestingggg::PetAPI,
          type: :"pet.moderation.approved"
        }

      class PetModerationApproved < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_accessor approved_at: Time

        attr_accessor pet: HelloWorldTestingggg::PetAPI

        attr_accessor type: :"pet.moderation.approved"

        def initialize: (
          approved_at: Time,
          pet: HelloWorldTestingggg::PetAPI,
          ?type: :"pet.moderation.approved"
        ) -> void

        def to_hash: -> {
          approved_at: Time,
          pet: HelloWorldTestingggg::PetAPI,
          type: :"pet.moderation.approved"
        }
      end

      type pet_moderation_rejected =
        {
          pet: HelloWorldTestingggg::PetAPI,
          reason: HelloWorldTestingggg::Models::PetModerationWebhookEvent::PetModerationRejected::reason,
          type: :"pet.moderation.rejected",
          review_notes: ::Array[HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote]
        }

      class PetModerationRejected < HelloWorldTestingggg::Internal::Type::BaseModel
        attr_accessor pet: HelloWorldTestingggg::PetAPI

        attr_accessor reason: HelloWorldTestingggg::Models::PetModerationWebhookEvent::PetModerationRejected::reason

        attr_accessor type: :"pet.moderation.rejected"

        attr_reader review_notes: ::Array[HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote]?

        def review_notes=: (
          ::Array[HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote]
        ) -> ::Array[HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote]

        def initialize: (
          pet: HelloWorldTestingggg::PetAPI,
          reason: HelloWorldTestingggg::Models::PetModerationWebhookEvent::PetModerationRejected::reason,
          ?review_notes: ::Array[HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote],
          ?type: :"pet.moderation.rejected"
        ) -> void

        def to_hash: -> {
          pet: HelloWorldTestingggg::PetAPI,
          reason: HelloWorldTestingggg::Models::PetModerationWebhookEvent::PetModerationRejected::reason,
          type: :"pet.moderation.rejected",
          review_notes: ::Array[HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote]
        }

        type reason = :policy_violation | :duplicate | :"unsafe-content"

        module Reason
          extend HelloWorldTestingggg::Internal::Type::Enum

          POLICY_VIOLATION: :policy_violation
          DUPLICATE: :duplicate
          UNSAFE_CONTENT: :"unsafe-content"

          def self?.values: -> ::Array[HelloWorldTestingggg::Models::PetModerationWebhookEvent::PetModerationRejected::reason]
        end

        type review_note =
          {
            message: String,
            reviewer: HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote::Reviewer
          }

        class ReviewNote < HelloWorldTestingggg::Internal::Type::BaseModel
          attr_accessor message: String

          attr_reader reviewer: HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote::Reviewer?

          def reviewer=: (
            HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote::Reviewer
          ) -> HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote::Reviewer

          def initialize: (
            message: String,
            ?reviewer: HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote::Reviewer
          ) -> void

          def to_hash: -> {
            message: String,
            reviewer: HelloWorldTestingggg::PetModerationWebhookEvent::PetModerationRejected::ReviewNote::Reviewer
          }

          type reviewer =
            {
              id: Integer,
              email: String,
              first_name: String,
              last_name: String,
              password: String,
              phone: String,
              username: String,
              user_status: Integer
            }

          class Reviewer < HelloWorldTestingggg::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader email: String?

            def email=: (String) -> String

            attr_reader first_name: String?

            def first_name=: (String) -> String

            attr_reader last_name: String?

            def last_name=: (String) -> String

            attr_reader password: String?

            def password=: (String) -> String

            attr_reader phone: String?

            def phone=: (String) -> String

            attr_reader username: String?

            def username=: (String) -> String

            attr_reader user_status: Integer?

            def user_status=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?email: String,
              ?first_name: String,
              ?last_name: String,
              ?password: String,
              ?phone: String,
              ?username: String,
              ?user_status: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              email: String,
              first_name: String,
              last_name: String,
              password: String,
              phone: String,
              username: String,
              user_status: Integer
            }
          end
        end
      end

      def self?.variants: -> ::Array[HelloWorldTestingggg::Models::pet_moderation_webhook_event]
    end
  end
end
