module HelloWorldTestingggg
  module Models
    type profile_retrieve_params =
      { profile_id: String }
      & HelloWorldTestingggg::Internal::Type::request_parameters

    class ProfileRetrieveParams < HelloWorldTestingggg::Internal::Type::BaseModel
      extend HelloWorldTestingggg::Internal::Type::RequestParameters::Converter
      include HelloWorldTestingggg::Internal::Type::RequestParameters

      attr_accessor profile_id: String

      def initialize: (
        profile_id: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> void

      def to_hash: -> {
        profile_id: String,
        request_options: HelloWorldTestingggg::RequestOptions
      }
    end
  end
end
