module HelloWorldTestingggg
  module Models
    type user_retrieve_params =
      { username: String }
      & HelloWorldTestingggg::Internal::Type::request_parameters

    class UserRetrieveParams < HelloWorldTestingggg::Internal::Type::BaseModel
      extend HelloWorldTestingggg::Internal::Type::RequestParameters::Converter
      include HelloWorldTestingggg::Internal::Type::RequestParameters

      attr_accessor username: String

      def initialize: (
        username: String,
        ?request_options: HelloWorldTestingggg::request_opts
      ) -> void

      def to_hash: -> {
        username: String,
        request_options: HelloWorldTestingggg::RequestOptions
      }
    end
  end
end
